backend:
  name: git-gateway
  branch: main  # Asegúrate de que sea el nombre correcto de tu rama
  
locale: 'es'

media_folder: "static/images"
public_folder: "/images"


collections:
  - name: "homepage"
    label: "Página inicio"
    files:
      - file: "content/home/_index.md"
        label: "Página de inicio"
        name: "homepage"
        fields:
          - { label: "Sección principal", name: "header", widget: "object", fields: [
              { label: "Video principal", name: "video", widget: "file" },
        
            ] }
          - { label: "Sección Bungalows", name: "bungalows", widget: "object", fields: [
              { label: "Encabezado Bungalows", name: "title", widget: "string" },
              { label: "Descripción Bungalows", name: "description", widget: "string" }
            ] }
          - { label: "Sección Eventos", name: "events", widget: "object", fields: [
              { label: "Título Eventos", name: "title", widget: "string" },
              { label: "Descripción Eventos", name: "description", widget: "string" }
            ] }
          - { label: "Evento 1", name: "event_1", widget: "object", fields: [
              { label: "Título de evento", name: "title", widget: "string" },
              { label: "Descripción de evento", name: "description", widget: "string" },
              { label: "Imagen de evento", name: "image", widget: "image" },
            ] }
          - { label: "Evento 2", name: "event_2", widget: "object", fields: [
              { label: "Título de evento", name: "title", widget: "string" },
              { label: "Descripción de evento", name: "description", widget: "string" },
              { label: "Imagen de evento", name: "image", widget: "image" },
            ] }
          - { label: "Evento 3", name: "event_3", widget: "object", fields: [
              { label: "Título de evento", name: "title", widget: "string" },
              { label: "Descripción de evento", name: "description", widget: "string" },
              { label: "Imagen de evento", name: "image", widget: "image" },
            ] }
          - { label: "Evento 4", name: "event_4", widget: "object", fields: [
              { label: "Título de evento", name: "title", widget: "string" },
              { label: "Descripción de evento", name: "description", widget: "string" },
              { label: "Imagen de evento", name: "image", widget: "image" },
            ] }


  - name: "bungalows"
    label: "Página Bungalows"
    files:
      - file: "content/bungalows.md"
        label: "Página de Bungalows"
        name: "bungalows"
        fields:
          - { label: "Seccion principal", name: "header", widget: "object", fields: [
              { label: "Encabezado", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Imagen", name: "image", widget: "image" },
              { label: "Hora de llegada", name: "hora_llegada", widget: "string" },
              { label: "Hora de salida", name: "hora_salida", widget: "string" }
            ] }
          - { label: "Philia card", name: "philia_card", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "string" }
            ] }
          - { label: "Eros card", name: "eros_card", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "string" }
            ] }
          - { label: "Agape card", name: "agape_card", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "string" }
            ] }
          - { label: "Philia sección", name: "philia_section", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Subtítulo", name: "subtitle", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" }
            ] }
          - { label: "Eros sección", name: "eros_section", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Subtítulo", name: "subtitle", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" }
            ] }
          - { label: "Agape sección", name: "agape_section", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Subtítulo", name: "subtitle", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" }
            ] }
          - { label: "Botón de reserva", name: "reserve_button", widget: "object", fields: [
              { label: "Link de reserva", name: "link", widget: "string" },
            ] }
          
  - name: "experiences"
    label: "Página Experiences"
    files:
      - file: "content/experiences.md"
        label: "Página de Experiences"
        name: "experiences"
        fields:
          - { label: "Seccion principal", name: "header", widget: "object", fields: [
              { label: "Encabezado", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" },
            ] }
          - { label: "Experience 1", name: "experience_one", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Imágen", name: "image", widget: "image" }
            ] }
          - { label: "Experience 2", name: "experience_two", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Imágen", name: "image", widget: "image" }
            ] }
          - { label: "Experience 3", name: "experience_three", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Imágen", name: "image", widget: "image" }
            ] }
          - { label: "Experience 4", name: "experience_four", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Imágen", name: "image", widget: "image" }
            ] }
          - { label: "Experience 5", name: "experience_five", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Imágen", name: "image", widget: "image" }
            ] }
          - { label: "Experience 6", name: "experience_six", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Imágen", name: "image", widget: "image" }
            ] }
          - { label: "Experience 7", name: "experience_seven", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Imágen", name: "image", widget: "image" }
            ] }
          - { label: "Experience 8", name: "experience_eight", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Imágen", name: "image", widget: "image" }
            ] }

  - name: "boutique"
    label: "Página Boutique"
    files:
      - file: "content/boutique.md"
        label: "Página de Boutique"
        name: "boutique"
        fields:
          - { label: "Seccion principal", name: "header", widget: "object", fields: [
              { label: "Encabezado", name: "title", widget: "string" },
              { label: "Banner", name: "banner", widget: "image" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Horario", name: "horario", widget: "string" },
            ] }
          - { label: "Galeria", name: "galeria", widget: "object", fields: [
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Imágen 1", name: "image_one", widget: "image" },
              { label: "Imágen 3", name: "image_three", widget: "image" },
              { label: "Imágen 4", name: "image_four", widget: "image" },
              { label: "Imágen 5", name: "image_five", widget: "image" },
            ] }
   
  - name: "cafe"
    label: "Página Cafe y Restaurante"
    files:
      - file: "content/cafe.md"
        label: "Página de Cafe y Restaurante"
        name: "cafe"
        fields:
          - { label: "Seccion principal", name: "header", widget: "object", fields: [
              { label: "Encabezado", name: "title", widget: "string" },
              { label: "Banner", name: "banner", widget: "image" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Horario", name: "horario", widget: "string" },
            ] }
          - { label: "Galeria", name: "galeria", widget: "object", fields: [
              { label: "Imágen 1", name: "image_one", widget: "image" },
              { label: "Imágen 2", name: "image_two", widget: "image" },
              { label: "Imágen 3", name: "image_three", widget: "image" },
              { label: "Imágen 4", name: "image_four", widget: "image" },
              { label: "Imágen 5", name: "image_five", widget: "image" },
              { label: "Imágen 6", name: "image_six", widget: "image" },
            ] }      
          - { label: "Menu", name: "menu", widget: "object", fields: [
              { label: "Titulo", name: "title", widget: "text" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Imágen", name: "image", widget: "image" },
              { label: "Url 1", name: "url", widget: "string" },
            ] }      
          