backend:
  name: git-gateway
  branch: main  # Asegúrate de que sea el nombre correcto de tu rama
  
locale: 'es'

media_folder: "assets/images"

collections:
  - name: "homepage"
    label: "Página inicio"
    files:
      - file: "content/home/index.md"
        label: "Contenido general"
        name: "homepage"
        fields:
          - { label: "Sección Bungalows", name: "bungalows", widget: "object", fields: [
              { label: "Encabezado Bungalows", name: "title", widget: "string" },
              { label: "Descripción Bungalows", name: "description", widget: "string" }
            ] }
          - { label: "Sección Eventos", name: "events", widget: "object", fields: [
              { label: "Título Eventos", name: "title", widget: "string" },
              { label: "Descripción Eventos", name: "description", widget: "string" }
            ] }