backend:
  name: git-gateway
  branch: main  # O el nombre de tu rama principal

media_folder: "static/img"  # Carpeta donde se guardarán las imágenes
public_folder: "/img"  # Ruta pública para acceder a las imágenes

collections:
  - name: "home"
    label: "Página Principal"
    folder: "content/home"  # Carpeta donde se guardará el archivo de contenido de la página principal
    create: true
    fields:
      - label: "Texto de Bienvenida"
        name: "welcome_text"
        widget: "text"  # Campo de texto para el texto que quieres cambiar
