backend:
  name: git-gateway
  branch: main  # Asegúrate de que sea el nombre correcto de tu rama

media_folder: "images/uploads"  # Carpeta donde se guardarán las imágenes

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - name: "index"
        label: "Página de inicio"
        file: "index.html"
        fields:
          - { name: "titulo", label: "Título", widget: "string" }
