backend:
  name: git-gateway
  branch: main  # Asegúrate de que sea el nombre correcto de tu rama

media_folder: "static/img"

collections:
  - name: "homepage"
    label: "Homepage"
    files: 
      - name: "index"
        label: "Página de inicio"
        file: "content/home.md"
        fields:
          - { name: "titulo", label: "Título", widget: "string" }
