backend:
  name: git-gateway
  branch: main  # Asegúrate de que sea el nombre correcto de tu rama

media_folder: "assets/images"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "content/home/index.md"
        label: "Homepage Settings"
        fields:
          - { label: "Header Text", name: "header", widget: "string" }
