backend:
  name: git-gateway
  branch: main  # Asegúrate de que sea el nombre correcto de tu rama
  
i18n: true
locale: 'es'

media_folder: "assets/images"

collections:
  - name: "homepage"
    label: "Pagina inicio"
    files:
      - file: "content/home/index.md"
        label: "Contenido general"
        name: "general"  # Agregado el campo 'name'
        fields:
          - { label: "Encabezado Bungalows", name: "bungalows_home_title", widget: "string" }
          - { label: "Descripción Bungalows", name: "bungalows_home_description", widget: "string" }