backend:
  name: git-gateway
  branch: main  # Asegúrate de que sea el nombre correcto de tu rama
  
locale: 'es'

media_folder: "static/images"
public_folder: "/images"


collections:
  - name: "homepage"
    label: "Página inicio"
    files:
      - file: "content/home/_index.md"
        label: "Página de inicio"
        name: "homepage"
        fields:
          - { label: "Sección Bungalows", name: "bungalows", widget: "object", fields: [
              { label: "Encabezado Bungalows", name: "title", widget: "string" },
              { label: "Descripción Bungalows", name: "description", widget: "string" }
            ] }
          - { label: "Sección Eventos", name: "events", widget: "object", fields: [
              { label: "Título Eventos", name: "title", widget: "string" },
              { label: "Descripción Eventos", name: "description", widget: "string" }
            ] }
          - { label: "Evento 1", name: "event_1", widget: "object", fields: [
              { label: "Título de evento", name: "title", widget: "string" },
              { label: "Descripción de evento", name: "description", widget: "string" },
              { label: "Imagen de evento", name: "image", widget: "image" },
            ] }
          - { label: "Evento 2", name: "event_2", widget: "object", fields: [
              { label: "Título de evento", name: "title", widget: "string" },
              { label: "Descripción de evento", name: "description", widget: "string" },
              { label: "Imagen de evento", name: "image", widget: "image" },
            ] }
          - { label: "Evento 3", name: "event_3", widget: "object", fields: [
              { label: "Título de evento", name: "title", widget: "string" },
              { label: "Descripción de evento", name: "description", widget: "string" },
              { label: "Imagen de evento", name: "image", widget: "image" },
            ] }
          - { label: "Evento 4", name: "event_4", widget: "object", fields: [
              { label: "Título de evento", name: "title", widget: "string" },
              { label: "Descripción de evento", name: "description", widget: "string" },
              { label: "Imagen de evento", name: "image", widget: "image" },
            ] }


  - name: "bungalows"
    label: "Página Bungalows"
    files:
      - file: "content/bungalows.md"
        label: "Página de Bungalows"
        name: "bungalows"
        fields:
          - { label: "Seccion principal", name: "header", widget: "object", fields: [
              { label: "Encabezado", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" },
              { label: "Imagen", name: "image", widget: "image" },
              { label: "Hora de llegada", name: "hora_llegada", widget: "string" },
              { label: "Hora de salida", name: "hora_salida", widget: "string" }
            ] }
          - { label: "Philia card", name: "philia_card", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "string" }
            ] }
          - { label: "Eros card", name: "eros_card", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "string" }
            ] }
          - { label: "Agape card", name: "agape_card", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Descripción", name: "description", widget: "string" }
            ] }
          - { label: "Philia sección", name: "philia_section", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Subtítulo", name: "subtitle", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" }
            ] }
          - { label: "Eros sección", name: "eros_section", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Subtítulo", name: "subtitle", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" }
            ] }
          - { label: "Agape sección", name: "agape_section", widget: "object", fields: [
              { label: "Título", name: "title", widget: "string" },
              { label: "Subtítulo", name: "subtitle", widget: "string" },
              { label: "Descripción", name: "description", widget: "text" }
            ] }
          - { label: "Botón de reserva", name: "reserve_button", widget: "object", fields: [
              { label: "Link de reserva", name: "link", widget: "string" },
            ] }
          
