backend:
  name: git-gateway
  branch: main  # Asegúrate de que sea el nombre correcto de tu rama
  
locale: 'es'

media_folder: "static/images"
public_folder: "/images"


collections:
  - name: "homepage"
    label: "Página inicio"
    files:
      - file: "content/home/index.md"
        label: "Página de inicio"
        name: "homepage"
        fields:
          - { label: "Sección Bungalows", name: "bungalows", widget: "object", fields: [
              { label: "Encabezado Bungalows", name: "title", widget: "string" },
              { label: "Descripción Bungalows", name: "description", widget: "string" }
            ] }
          - { label: "Sección Eventos", name: "events", widget: "object", fields: [
              { label: "Título Eventos", name: "title", widget: "string" },
              { label: "Descripción Eventos", name: "description", widget: "string" }
            ] }
          - { label: "Evento 1", name: "event_1", widget: "object", fields: [
              { label: "Título de evento", name: "title", widget: "string" },
              { label: "Descripción de evento", name: "description", widget: "string" },
              { label: "Imagen de evento", name: "image", widget: "image" },
            ] }
          - { label: "Evento 2", name: "event_2", widget: "object", fields: [
              { label: "Título de evento", name: "title", widget: "string" },
              { label: "Descripción de evento", name: "description", widget: "string" },
              { label: "Imagen de evento", name: "image", widget: "image" },
            ] }
          - { label: "Evento 3", name: "event_3", widget: "object", fields: [
              { label: "Título de evento", name: "title", widget: "string" },
              { label: "Descripción de evento", name: "description", widget: "string" },
              { label: "Imagen de evento", name: "image", widget: "image" },
            ] }
          - { label: "Evento 4", name: "event_4", widget: "object", fields: [
              { label: "Título de evento", name: "title", widget: "string" },
              { label: "Descripción de evento", name: "description", widget: "string" },
              { label: "Imagen de evento", name: "image", widget: "image" },
            ] }
          

  - name: "experiences"
    label: "Experiencias"
    files:
      - file: "content/experiences/index.md"
        label: "Página de experiencias"
        name: "experiencias"
        fields:
          - { label: "Título principal", name: "title", widget: "string" }
          - { label: "Descripción", name: "description", widget: "text" }
          - label: "Sección de experiencias"
            name: "experiancias"
            widget: "list"
            fields:
              - { label: "Experiencia 1", name: "experiencia_1", widget: "object", fields: [
                { label: "Nombre de experiencia", name: "title", widget: "string" },
                { label: "Imagen de experiencia", name: "image", widget: "image" }
              ] }
              - { label: "Experiencia 2", name: "experiencia_2", widget: "object", fields: [
                { label: "Nombre de experiencia", name: "title", widget: "string" },
                { label: "Imagen de experiencia", name: "image", widget: "image" }
              ] }
              - { label: "Experiencia 3", name: "experiencia_3", widget: "object", fields: [
                { label: "Nombre de experiencia", name: "title", widget: "string" },
                { label: "Imagen de experiencia", name: "image", widget: "image" }
              ] }
              - { label: "Experiencia 4", name: "experiencia_4", widget: "object", fields: [
                { label: "Nombre de experiencia", name: "title", widget: "string" },
                { label: "Imagen de experiencia", name: "image", widget: "image" }
              ] }
              - { label: "Experiencia 5", name: "experiencia_5", widget: "object", fields: [
                { label: "Nombre de experiencia", name: "title", widget: "string" },
                { label: "Imagen de experiencia", name: "image", widget: "image" }
              ] }
              - { label: "Experiencia 6", name: "experiencia_6", widget: "object", fields: [
                { label: "Nombre de experiencia", name: "title", widget: "string" },
                { label: "Imagen de experiencia", name: "image", widget: "image" }
              ] }
              - { label: "Experiencia 7", name: "experiencia_7", widget: "object", fields: [
                { label: "Nombre de experiencia", name: "title", widget: "string" },
                { label: "Imagen de experiencia", name: "image", widget: "image" }
              ] }
              - { label: "Experiencia 8", name: "experiencia_8", widget: "object", fields: [
                { label: "Nombre de experiencia", name: "title", widget: "string" },
                { label: "Imagen de experiencia", name: "image", widget: "image" }
              ] }
          